version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
