name: ✅ test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  test:
    uses: react-component/rc-test/.github/workflows/test-utoo.yml@main
    secrets:

      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
